name: LSTM_Season2_w_huber
version: 0.0.1

architecture: 
  type: "LSTM_SMW"
  hidden: 10

hyperparameters:
  batch_size: 32
  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 0.0001
  optimizer: "Adam"
  loss: "Huber"
  epoches: 50

window:
  past: int
  forecast: int

files:
  training: "./data/csv_files/field_f2"
  test: "./data/csv_files/field_f4"

features:
  input:
    fiedls: ['s_b','s_w','LAI','irr']
    meteo_historical: ['temperature_2m']
    meteo_forecast: ['temperature_2m_f']
  output: ['s_b','s_w']
  input_seq_len: 72
  output_seq_len: 48
  shift: 0
  geo_coordinate:
    lat: 52.52
    lon: 13.41

irr_param:
  durartio: 
    a: -4.99
    b: 137.97
  volume:
    a: -3.16
    b: 87.22
  threshold: 22.0

