name: LSTM_Season2_w
version: 0.0.1

architecture: 
  type: "LSTM_SMW"
  hidden: 20

hyperparameters:
  batch_size: 32
  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 0.0001
  optimizer: "SGD"
  loss: "MSELoss"
  epoches: 50

window:
  past: int
  forecast: int

files:
  training: "./data/csv_files/field_f2"
  test: "./data/csv_files/field_f4"

features:
  input:
    fiedls: ['s_b','s_w','LAI','irr']
    meteo_historical: ['temperature_2m','relative_humidity_2m','cloud_cover','wind_speed_10m','wind_direction_100m','soil_temperature_0_to_7cm','soil_temperature_28_to_100cm','rain','precipitation','evapotranspiration']
    meteo_forecast: ['temperature_2m_f','relative_humidity_2m_f','cloud_cover_f','wind_speed_10m_f','wind_direction_10m_f','rain_f']
  output: ['s_b','s_w']
  input_seq_len: 72
  output_seq_len: 48
  shift: 0
  geo_coordinate:
    lat: 52.52
    lon: 13.41

irr_param:
  durartio: 
    a: -4.99
    b: 137.97
  volume:
    a: -3.16
    b: 87.22
  threshold: 22.0

